# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.7
maven_group = net.pixeldreamstudios.spw
archives_name = spell_powered_weapons
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.19.3
fabric_api_version = 0.116.14+1.21.1
neoforge_version = 21.1.215

# Spell Engine (CurseForge project 807653)
spell_engine_fabric_file = 8786005
spell_engine_neoforge_file = 8786009

# Spell Power (CurseForge project 771265)
spell_power_fabric_file = 8473364
spell_power_neoforge_file = 8472570

# More RPG Library (CurseForge project 923030) - optional compat
more_rpg_library_fabric_file = 8479277
more_rpg_library_neoforge_file = 8479312

# Ranged Weapon API (CurseForge project 962162)
ranged_weapon_api_fabric_file = 7291833
ranged_weapon_api_neoforge_file = 7291834

# MmmMmmMmmMmm (CurseForge project 225738) - optional compat
dummmmmmy_fabric_file = 7943677
dummmmmmy_neoforge_file = 7943676

tiny_config_version = 3.1.0
